### ISSUE TITLE
如何实现水平垂直居中？

### ISSUE THREAD

**Issue by BetaSu** [BetaSu/fe-hunter#26]
### 要回答的问题

实现水平垂直居中布局

### 最佳答案评选标准

 

1. 请从以下角度回答该问题：

  - 元素定宽高
  - 元素不定宽高

2. 多种实现方式是加分项

## 最佳答案

[c0dedance的回答](https://github.com/BetaSu/fe-hunter/issues/26#issuecomment-1080095904)

### 答题同学须知

- 答题规范：请在`一次评论`中完成作答，后续修改也请编辑该评论，而不是追加新的评论

- 评选标准：最佳答案由`围观同学`的 👍 和[卡颂](https://github.com/BetaSu)共同决定

- 评选时间：一般是当日18：00左右评选，如果问题发布当天回答数较少，问题悬赏金额可能增加，同时悬赏时间也会增加

### 围观同学须知

- 对于你满意的答案，请不要吝惜你的 👍，这是评选**最佳答案**的依据

- `非答题的评论`会被删除，问题相关讨论请在[赏金猎人群](https://github.com/BetaSu/fe-hunter)中进行

**Comment by Yill625** [comment]
https://juejin.cn/post/6941206439624966152#heading-43

**Comment by shabbyaaa** [comment]
flex一把梭哈

**Comment by c0dedance** [comment]
1. flex布局，无需考虑父子宽高

    ~~~css
    /* 父元素设置 */
    display: flex;
    justify-content: center;
    align-items: center;
    ~~~

2. 相对定位+transform，无需考虑父子宽高

    ~~~css
    /* 子元素设置 */
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    ~~~

3. display：table-cell

    ~~~css
    .parent {
      width: 500px;
      height: 500px;
      background-color: pink;
      display: table-cell;
      vertical-align: middle;
      text-align: center;
    }
    .child {
      width: 200px;
      height: 200px;
      background-color: skyblue;
      display: inline-block;
    }
    ~~~

4. 相对定位 + 具体magin

	```css
   position: absolute;
   top: 50%;
   left: 50%;
   margin-top: 手动计算;
   margin-left: 手动计算;
   ```
   
5. magin auto，父元素宽高可以不确定，子元素没有具体宽高会铺满父元素

	```css
    position: absolute;
    margin: auto;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
   ```
   
6. 手动计算具体magin，父子元素宽高需要确定

    ```
    margin-top: 手动计算;
    margin-left: 手动计算;
    ```

**Comment by HXML** [comment]
方法1：绝对定位+margin:auto
    div{
        width: 200px;
        height: 200px;
        background: green;
        
        position:absolute;
        left:0;
        top: 0;
        bottom: 0;
        right: 0;
        margin: auto;
    }
方法2：绝对定位+负margin
    div{
        width:200px;
        height: 200px;
        background:green;
        
        position: absolute;
        left:50%;
        top:50%;
        margin-left:-100px;
        margin-top:-100px;
    }
方法3：绝对定位+transform
    div{
        width: 200px;
        height: 200px;
        background: green;
        
        position:absolute;
        left:50%;    /* 定位父级的50% */
        top:50%;
        transform: translate(-50%,-50%); /*自己的50% */
    }
方法4：flex布局
   .box{
         height:600px;  
         
         display:flex;
         justify-content:center;  //子元素水平居中
         align-items:center;      //子元素垂直居中
           /* aa只要三句话就可以实现不定宽高水平垂直居中。 */
    }
    .box>div{
        background: green;
        width: 200px;
        height: 200px;
    }
方法5：table-cell实现居中
display:table-cell;
text-align:center;
vertical-align: middle;

**Comment by muyeyong** [comment]
1：元素定宽高
`position: absolute
top: 50%
left: 50%
transform: translate(-50%, 50%);
`
2：元素不定宽高
`display: flex
justify-content: center
align-item: center
`

**Comment by CrisChr** [comment]
方法一：绝对定位与负边距（已知宽高）
`#container {
      position: relative;
    }
 #center {
      position: absolute;
      top: 50%;
      left: 50%;
      margin: -50px 0 0 -50px;
    }`

方法二：绝对定位margin:auto （已知宽高）
` #container {
      position: relative;
      height:100px;//必须有个高度
    }
 #center {
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      margin: auto;//注意此处的写法
    }`

方法三：绝对定位+css3（未知元素宽高）
`  #container {
      position: relative;
    }
  #center {
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
    }`

方法四：flex
` #container {//直接在父容器设置即可
      height: 100vh;//必须有高度
      display: flex;
      justify-content: center;
      align-items: center;
    }`

方法五：flex/grid和margin: auto
`#container {
      height: 100vh;//必须有高度
      display: grid;
    }
  #center {
      margin: auto;
    }`

**Comment by tangdingga1** [comment]
## 元素定宽高
父元素的宽高为pw,ph。子元素的宽高为cw,ch。

### 流式布局
```css
.child {
  margin: calc((ph - ch) / 2) auto;
}
```
### 改变元素盒属性
```css
.parent {
  line-height: ph;
  text-align: center;
}
.child {
  display: inline-block;
}
```

## 元素不定宽高
### flex大法好
```css
.parent {
  display: flex;
  align-items: center;
  justify-content: center;
}
```
### 绝对定位
```css
.parent {
  position: relative;
}

.child {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translateX(-50%) translateY(-50%);
}
```
### table
```css
.parent {
    display: table-cell;
    vertical-align: middle;
    text-align: center;
}
.child {
    display: inline-block;
}
```

**Comment by lilililanhui** [comment]
- 水平居中
  - inline元素：`text-align:center`(不需要知道尺寸)
  - block元素：`margin:auto`(不需要知道尺寸)
  - absolute元素：`left: 50%`+`margin-left:-${自身宽度}/2`
- 垂直居中
  - inline元素：`line-height:${容器高度}`
  - absolute元素：`top:50%`+`margin-top:-${自身高度}/2`
- 水平垂直居中
  - flex布局：`flex-direction`+`justify-content:center`+`align-items:center`(不需要知道尺寸)
  - absolute元素：`top:50%`+`left:50%`+ `transform: translate(-50%,-50%)`(不需要知道尺寸)
    - CSS3的特性 ，浏览器的兼容性可能会差一点
  - absolute元素：`top:0`+`bottom:0`+`left:0`+`right:0`+`margin:auto`(不需要知道尺寸)
    - 既要保证兼容性，又要保证子元素是未知的，可以用该方法，margin自动填充 
  - absolute元素：`top:calc(50% - ${高度}/2)`+`left:calc(50% - ${宽度}/2)`

**Comment by blackcoffeecat** [comment]
不定宽高的居中方式, 这些居中元素的大小可以被内容撑开，依旧保持居中
1. flex布局
```css
.container {
    display: flex;
    align-items: center;
    justify-content: center;
}
```

2. inline-block布局
```css
.container {
    text-align: center;
    white-space: nowrap;
}
.container::before {
    content: "";
    display: inline-block;
    width: 0;
    height: 100%;
    vertical-align: middle;
}
.center-box {
    display: inline-block;
    line-height: 100%;
    vertical-align: middle;
    border: 1px solid red;
}
```

需要确定宽高的居中方式：
3. position + margin 
```css
.container {
   position: relative;
}
.center-box {
    width: ...;
    height: ...;
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    margin: auto;
}
```

4.transform 
```css
.center-box {
    width: ...;
    height: ...;
    margin-top: 50%;
    margin-left: 50%;
    transform: translate(-50%, -50%)
}
```

兼容性方面，应该是2和3兼容性最好，但是超出父元素大小的时候会对齐在左上角。
附上codepen：https://codepen.io/blackcoffeecat/pen/MWrmWmX

**Comment by dawnkie** [comment]
# 元素居中

>  **目标元素，指被居中的元素**

## 01- 水平居中

<font color=red>**行内元素 `inline` or ` inline-*`**</font>

```js
父元素 {
  display: block; 		// 父元素必须为块级元素
  text-align: center;
}
```

<font color=red>**块级元素 `block-level`**</font>

```js
// 仅适用于未浮动的情况
目标元素 {
  margin-left: auto;
  margin-right: auto;	// margin: 0 auto;
  width: xxx;			// max-width: xxx;
}
```

<font color=red>**多个块级元素 `block-level`**</font>

**(1) 内联可居中特性 (前提：父元素为块级元素)**

```js
父元素 {
	text-align: center;
}
目标元素 {
	display: inline-block;
	width: xxx; 		// max-width: xxx;
}
```

  **(2) 弹性布局**

```js
父元素 {
	display: flex;
	justify-content: center;
}
目标元素 {
	width: xxx; 		// max-width: xxx;
}
```

  **(3) 自动外填充**

```js
目标元素 {
	margin-left: auto;
	margin-right: auto;	// margin: 0 auto;
	width: xxx; 			// max-width: xxx;
}
```

## 02- 垂直居中

<font color=red>**行内元素 `inline` or ` inline-*`**</font>

**(1)  父元素设置等大的上下内填充**

```js
父元素 {
	padding-top: 30px;
	padding-bottom: 30px;
}
```

  **(2)  父元素设置相同的`line-height`与`height` (缺点：带换行不能完全居中)**

```css
父元素 {
	height: 100px;
	line-height: 100px;
	white-space: nowrap;
}
```

  **(3) 表格式**

```css
父元素 {
	display: table;
}
目标元素 {
	display: table-cell;
	vertical-align: middle;
}
```

  **(3) 弹性布局 (前提：父元素必须设置高度)**

```css
父元素 {
	display: flex;
	justify-content: center;
	flex-direction: column;
	height: 400px;
}
```

  **(4) 相对布局 + 幽灵元素**

```css
父元素 {
	position: relative;
}
父元素::before {	// ::before和::after 表示在元素的前后添加内容
	content: " ";
	display: inline-block;
	height: 100%;
	width: 1%;
	vertical-align: middle;
}
目标元素 {
	display: inline-block;
	vertical-align: middle;
}
```

<font color=red>**块级元素 `block-level`**</font>

**(1) 情况一 目标元素高度已知**

```css
父元素 {
	position: relative;
}
目标元素 {
	position: absolute;
	top: 50%;
	height: 100px;
	margin-top: -50px;
}
```

  **(2) 情况二 目标元素高度未知**

```css
父元素 {
	position: relative;
}
目标元素 {
	position: absolute;
	top: 50%;
	transform: translateY(-50%);
}
```

  **(3) 表格式**

```js
// 缺点：目标元素的非内容区会垂向伸张
父元素 {
	display: table;
}
目标元素 {
	display: table-cell;
	vertical-align: middle;
}
```

  **(4) 弹性布局**

```css
父元素 {
	display: flex;
	flex-direction: column;
	justify-content: center;	// 或 目标元素 `margin: auto;`
}
```

## 03- 双向居中

- **情况一 目标元素长宽已知**

```css
父元素 {
	position: relative;
}

目标元素 {
	width: 300px;
	height: 100px;
	padding: 20px;

	position: absolute;
	top: 50%;
	left: 50%;

	transform: translate(-50%, -50%);	// margin: -50px 0 0 -150px;
}
```

- **情况二 目标元素长宽未知**

```css
父元素 {
	position: relative;
}
目标元素 {
	position: absolute;
	top: 50%;
	left: 50%;
	transform: translate(-50%, -50%);
}
```

```css
父元素 {
	position: relative;
	width: 142px;
	height: 142px;
}
目标元素 {
	position: absolute;
	top: 0;
	right: 0;
	left: 0;
	bottom: 0;
	margin: auto;
}
```

- **弹性布局**

```css
父元素 {
	display: flex;
	justify-content: center;
	align-items: center;
}
```

#
