### ISSUE TITLE
实现核辐射警告标志

### ISSUE THREAD

**Issue by BetaSu** [BetaSu/fe-hunter#38]
### 要实现的功能

核辐射警告标志是一个 60 度扇形黄、黑相间的圆。请使用 html 和 css 在网页中始终垂直、水平居中显示一个半径 100px 的核辐射警告标志图，效果如下图：

![image](https://user-images.githubusercontent.com/15828041/160957545-4949dad0-1643-43da-a8bf-a9f7246fa1db.png)

### 代码示例

html:

```html
<div>...</div>
```

css:

```css
div {
  /*  ... */
}
```

### 最佳答案评选标准

1. 请写出实现思路、代码，并为代码的关键步骤增写注释
2. 尽可能少使用的DOM元素
3. 不需要考虑浏览器的兼容性

## 最佳答案

[Haifeng-L的回答](https://github.com/BetaSu/fe-hunter/issues/38#issuecomment-1084144160)

### 答题同学须知

- 答题规范：请在`一次评论`中完成作答，后续修改也请编辑该评论，而不是追加新的评论

- 评选标准：最佳答案由`围观同学`的 👍 和[卡颂](https://github.com/BetaSu)共同决定

- 评选时间：一般是问题发布24小时后评选，如果问题发布当天回答数较少，问题悬赏金额可能增加，同时悬赏时间也会增加

### 围观同学须知

- 对于你满意的答案，请不要吝惜你的 👍，这是评选**最佳答案**的依据

- `非答题的评论`会被删除，问题相关讨论请在[赏金猎人群](https://github.com/BetaSu/fe-hunter)中进行

**Comment by wenda10086** [comment]
代码比较拙劣，先蹭一下暴力解
思路：先画一个小盒子，盒子内画半圆，然后旋转至指定角度画出弧
再拼借6个小盒子
```
<style>
    /* 整个盒子 */
    .box{
      width: calc(2 * var(--radius));
      height: calc(2 * var(--radius));
      position: relative;
    }
    /* 单个小盒子 */
    .father{
      width: var(--radius);
      height: var(--radius);
      overflow: hidden;
      position: absolute;
      left: 0;
      bottom: 0;
      transform-origin: right top;
    }
    .father:nth-child(2n) {
      color: yellow;
    }
    /* 弧 */
    .hu{
      width: calc(2 * var(--radius));
      height: var(--radius);
      border-radius: 0 0 var(--radius) var(--radius);
      background-color: currentColor;
      position: absolute;
      left: 0;
      bottom: 0;
      transform-origin: top;
      transform: rotate(120deg);
    }
    .rotate1{
      transform: rotate(-120deg);
    }
    .rotate2{
      transform: rotate(-60deg);
    }
    .rotate3{
      transform: rotate(60deg);
    }
    .rotate4{
      transform: rotate(120deg);
    }
    .rotate5{
      transform: rotate(180deg);
    }
  </style>
```
```
<div class="box" style="--radius: 100px">
  <div class="father rotate1">
    <div class="hu"></div>
  </div>
  <div class="father rotate2">
    <div class="hu"></div>
  </div>
  <div class="father">
    <div class="hu"></div>
  </div>
  <div class="father rotate3">
    <div class="hu"></div>
  </div>
  <div class="father rotate4">
    <div class="hu"></div>
  </div>
  <div class="father rotate5">
    <div class="hu"></div>
  </div>
</div>
```

**Comment by iwestlin** [comment]
谢邀，这题很简单啊，看我的：
```css
#nuclear {
  width: 200px;
  height: 200px;
  background-image: url('data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPScxLjEnIHhtbG5zPSdodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZycgeG1sbnM6eGxpbms9J2h0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsnIHg9JzBweCcgeT0nMHB4JyB2aWV3Qm94PScwIDAgNTEyIDUxMicgc3R5bGU9J2VuYWJsZS1iYWNrZ3JvdW5kOm5ldyAwIDAgNTEyIDUxMjsnIHhtbDpzcGFjZT0ncHJlc2VydmUnPjxwYXRoIHN0eWxlPSdmaWxsOiM2NjY2NjY7JyBkPSdNMjU2LDBjMTQxLjM3OCwwLDI1NiwxMTQuNjA5LDI1NiwyNTZTMzk3LjM3OCw1MTIsMjU2LDUxMkMxMTQuNjA5LDUxMiwwLDM5Ny4zOTEsMCwyNTYgUzExNC42MDksMCwyNTYsMHonLz48cGF0aCBzdHlsZT0nZmlsbDojRkNCQjI5OycgZD0nTTI1NiwzNi4wOTVjMTIxLjQ1LDAsMjE5LjkwNSw5OC40NTYsMjE5LjkwNSwyMTkuOTA1UzM3Ny40NSw0NzUuOTA1LDI1Niw0NzUuOTA1IFMzNi4wOTUsMzc3LjQ1LDM2LjA5NSwyNTZTMTM0LjU1LDM2LjA5NSwyNTYsMzYuMDk1eicvPjxnPjxwYXRoIHN0eWxlPSdmaWxsOiM0RDRENEQ7JyBkPSdNMjU2LDIyNi4wMzdjMTYuNTQsMCwyOS45NjMsMTMuNDIzLDI5Ljk2MywyOS45NjNTMjcyLjU0LDI4NS45NjMsMjU2LDI4NS45NjMgYy0xNi41NjYsMC0yOS45NjMtMTMuNDIzLTI5Ljk2My0yOS45NjNTMjM5LjQzNCwyMjYuMDM3LDI1NiwyMjYuMDM3eicvPjxwYXRoIHN0eWxlPSdmaWxsOiM0RDRENEQ7JyBkPSdNMjg0LjIzNywzMDcuNTAxbDYxLjgwNywxMDkuNTA4Yy0yNi41ODgsMTUuMDQ2LTU3LjMyNCwyMy42MjUtOTAuMDQ0LDIzLjYyNSBjLTMzLjM3NywwLTY0LjY1NC04LjkxNC05MS42MTUtMjQuNTE0bDYyLjg3Ni0xMDguOTAzYzguNDUsNC44OTUsMTguMjY2LDcuNzAzLDI4LjczOSw3LjcwMyBDMjY2LjI1NCwzMTQuOTIxLDI3NS44ODksMzEyLjIyOSwyODQuMjM3LDMwNy41MDF6Jy8+PHBhdGggc3R5bGU9J2ZpbGw6IzRENEQ0RDsnIGQ9J000MzkuMTY2LDI1Ny40NTZIMzEzLjQ1M2MwLTIxLjA2Mi0xMS4zMjMtMzkuNDctMjguMjUtNDkuNDY2bDYzLjkzMi0xMDguMjg0IEM0MDMuMDMzLDEzMS41ODgsNDM5LjE2NiwxOTAuMzAzLDQzOS4xNjYsMjU3LjQ1NnonLz48cGF0aCBzdHlsZT0nZmlsbDojNEQ0RDREOycgZD0nTTE2Mi44NTIsOTkuNzA1bDYzLjkzMiwxMDguMjg0Yy0xNi45MTQsOS45OTYtMjguMjUsMjguNDA0LTI4LjI1LDQ5LjQ2Nkg3Mi44MjEgQzcyLjgyMSwxOTAuMzAzLDEwOC45NjcsMTMxLjU4OCwxNjIuODUyLDk5LjcwNXonLz48L2c+PGc+PC9nPjxnPjwvZz48Zz48L2c+PGc+PC9nPjxnPjwvZz48Zz48L2c+PGc+PC9nPjxnPjwvZz48Zz48L2c+PGc+PC9nPjxnPjwvZz48Zz48L2c+PGc+PC9nPjxnPjwvZz48Zz48L2c+PC9zdmc+');
}
```
长得不像不怪我嗷，人svg就长这样：https://www.svgrepo.com/svg/193192/radiation-nuclear

**Comment by blackcoffeecat** [comment]
分成上下两部分绘制，使用伪类元素以减少dom元素
用了画三角形的思路， 中间是个等边三角形满足夹角为60度的图案
用position + margin方式实现元素居中，父元素为body

```html
<div class="nuclear-warn"></div>
<script>
  const {sqrt, pow} = Math;
  // 把等腰三角形分成两个直角三角形，计算垂直边长，作为:before,:after的高度
  const a = 200; // 等边三角形变长
  const b = a / 2;
  const c = sqrt(pow(a, 2) - pow(b, 2));
  console.log(c); // 约等于173
</script>
<style>
    /* 居中容器样式 */
    body {
        width: 100vw;
        height: 100vh;
        position: relative;
    }

    .nuclear-warn {
        width: 200px;
        height: 200px;
        /* 垂直水平居中 */
        position: absolute;
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;
        margin: auto;

        border-radius: 100px;
        overflow: hidden;
        font-size: 0;
    }

    .nuclear-warn::before,
    .nuclear-warn::after {
        content: "";
        display: block;
        height: 173px; /* 边长200px的等腰三角形高度*/
        box-sizing: border-box;
    }

    .nuclear-warn::before {
        margin-top: -73px;
        border-top: 173px solid yellow;
        border-left: 100px solid black;
        border-right: 100px solid black;
    }

    .nuclear-warn::after {
        border-left: 100px solid yellow;
        border-right: 100px solid yellow;
        border-bottom: 173px solid black;
    }
</style>
```

**Comment by Haifeng-L** [comment]
### 借助CSS3 conic-gradient锥形渐变,应该是最简单最直接的方法。

```
<div class="sign"></div>
<style>
  .sign {
    width: 100px;
    height: 100px;
    border-radius: 50px;

    position: absolute;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%) rotate(30deg);  /* 1.相对父级元素垂直水平居中 2.调整起笔角度 */

    background: repeating-conic-gradient(
      black,
      black 60deg, /* 黑色转60度 */
      yellow 60deg, 
      yellow 120deg /* 黄色转60度 */
    );
  }
</style>
```
效果：
<img width="153" alt="截屏2022-03-31 14 50 26" src="https://user-images.githubusercontent.com/29189636/160997201-094b13d8-354c-4b62-823e-f7768600108d.png">

或者
```
<style>
background: conic-gradient(
      rgba(0, 0, 0, 1),
      rgba(0, 0, 0, 1) 60deg, // 黑色转60度
      rgba(255, 255, 0, 1) 60deg, 
      rgba(255, 255, 0, 1) 120deg, // 黄色转60度
      rgba(0, 0, 0, 1) 120deg,
      rgba(0, 0, 0, 1) 180deg, // 黑色转60度
      rgba(255, 255, 0, 1) 180deg,
      rgba(255, 255, 0, 1) 240deg, // 黄色转60度
      rgba(0, 0, 0, 1) 240deg,
      rgba(0, 0, 0, 1) 300deg,  // 黑色转60度
      rgba(255, 255, 0, 1) 300deg,
      rgba(255, 255, 0, 1)// 黄色转60度
    );
</style>
```

**Comment by CrzMarvin** [comment]
一个div就行：
```html
<div class="radiation"></div>
```
```css
.radiation {
  width: 200px;
  height: 200px;
  border-radius: 50%;
  background: conic-gradient( 
    yellow 0deg 30deg, black 30deg 90deg, yellow 90deg 150deg, black 150deg 210deg, yellow 210deg 270deg, black 270deg 330deg, yellow 330deg 360deg );
}
```

**Comment by namejiang** [comment]
css3 的强大你无法想象

```
<div id="grad1"></div>
```
```
<style>
#grad1 {
  height: 200px;
  width: 200px;
  background-image: repeating-conic-gradient(black 0deg 45deg, yellow 45deg 90deg);
  border-radius: 50%;
}
</style>
```

![image](https://user-images.githubusercontent.com/23330897/161244029-9401fd14-9e51-4984-927c-01ca5e743187.png)

**Comment by supermanklk** [comment]
**神奇的 conic-gradient 圆锥渐变-实现核辐射图** 

`彩蛋：实现三角形再也不通过border的透明度了，也可以通过 conic-gradient`

1、css3引入的3个特性
```javascript
background: conic-gradient  // 圆锥渐变
background: linear-gradient // 线性渐变
background: radial-gradient // 光晕渐变
```
效果图分别如下，通过效果图我们能够看出实现核辐射图需要使用到圆锥渐变

<img width="653" alt="企业微信截图_85388524-1ead-4dc0-85c1-45dd9e6486d6" src="https://user-images.githubusercontent.com/28639384/161245000-7a9bb0a1-cafe-4120-9d94-5efe601638b7.png">

如图的圆锥渐变关键代码如下:
```css
{
    width: 200px;
    height: 200px;
    border-radius: 50%;
    // 这样出来的颜色之间没有隔离，是线性的
    background: conic-gradient(red, orange, yellow, green, teal, blue, purple);
}
```

`我们要实现的效果图需要颜色之间的完全隔离，因此可以使用如下代码实现`

```css
background: conic-gradient(yellow 0, yellow 30deg, black 30deg, black 90deg,yellow 90deg, yellow 150deg, black 150deg, black 210deg,yellow 210deg, yellow 270deg, black 270deg, black 330deg, yellow 330deg, yellow 36deg)
```

<img width="235" alt="image" src="https://user-images.githubusercontent.com/28639384/161245585-66ef6f59-b456-471a-bae3-287ae69a6a59.png">


2、彩蛋，如果通过 conic-geadient 实现三角形

```css
 {
      width: 200px;
      height: 200px;
      position: absolute;
      left: 50%;
      top: 50%;
      transform: translate(-50%, -50%);
      background: conic-gradient(yellow 0deg, yellow 135deg, red 135deg, red 225deg, yellow 225deg, yellow 360deg)
}
```

<img width="240" alt="image" src="https://user-images.githubusercontent.com/28639384/161246991-45db95de-7683-471f-ba84-27717aa2ca27.png">


进一步完善,通过transparent进行透明
```css
 {
      width: 200px;
      height: 200px;
      position: absolute;
      left: 50%;
      top: 50%;
      transform: translate(-50%, -50%);
      background: conic-gradient(transparent 0deg, transparent 135deg, red 135deg, red 225deg, transparent 225deg, transparent 360deg)
  }
```

<img width="237" alt="image" src="https://user-images.githubusercontent.com/28639384/161247442-94016086-7649-49e5-89fe-df7713d56459.png">

**Comment by claviering** [comment]
## Using conic-gradient 

```html
<div class="radiation-warning"></div>
```
```css
.radiation-warning {
  width: 100px;
  height: 100px;
  background: conic-gradient(
    yellow 0deg 60deg,
    black 60deg 120deg,
    yellow 120deg 180deg,
    black 180deg 240deg,
    yellow 240deg 300deg,
    black 300deg 360deg
  );
}
```
Result:
![1](https://user-images.githubusercontent.com/16227832/161361731-ca862e05-a020-4ff4-87e7-b20dd861bd36.png)

## Add a radius and rotate

```css
border-radius: 50%;
transform: rotate(-30deg);
```
Result:

![2](https://user-images.githubusercontent.com/16227832/161361810-905947e5-5281-4f4a-97f8-b33c5f892eae.png)

## Repeating-conic-gradient

```css
.radiation-warning {
  width: 100px;
  height: 100px;
  border-radius: 50%;
  transform: rotate(-30deg);
  background: repeating-conic-gradient(
    from 0deg,
    yellow 0deg 60deg,
    black 60deg 120deg
  );
}
```
Result:

![2](https://user-images.githubusercontent.com/16227832/161361810-905947e5-5281-4f4a-97f8-b33c5f892eae.png)

## Add the circle

```css
.radiation-warning::after{
  content: "";
  position: absolute;
  width: 40px;
  height: 40px;
  border-radius: 50%;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  background: radial-gradient(
    rgb(36, 31, 33) 13px,
    rgb(242, 215, 74) 13px
  );
}
```
Result:

![3](https://user-images.githubusercontent.com/16227832/161374694-de40202f-a704-4c8e-86e2-59e4831cf312.png)

## One more thing
add the border
```css
.radiation-warning {
  border: 10px solid rgb(242, 215, 74);
}
.radiation-warning::before{
  content: "";
  position: absolute;
  width: 120px;
  height: 120px;
  border-radius: 50%;
  border: 5px solid rgb(36, 31, 33);
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
```
Result:

![4](https://user-images.githubusercontent.com/16227832/161375304-d6e0f11c-663f-4c3b-b5c3-78222c561708.png)

## Online Demo

[codepen](https://codepen.io/claviering/pen/abEVBgZ)

## Reference
> https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/conic-gradient
> https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/repeating-conic-gradient
